image: Visual Studio 2015

environment:
  PYTHON: C:\Python35-x64

install:
 - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
 - "python --version"

platform:
 - x86
 - x64

configuration:
 - Debug
 - Release

build:
  parallel: true
  project: vs/vs2015/ducible.sln
