image: Visual Studio 2015

environment:
  PYTHON: C:\Python35-x64

install:
 - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
 - "python --version"

platform:
 - Win32
 - x64

configuration:
 - Debug
 - Release

build:
  parallel: true
  project: vs/vs2015/ducible.sln

artifacts:
 - path: vs\vs2015\$(platform)\$(configuration)\ducible.exe
   name: ducible

deploy:
 - provider: GitHub
   auth_token:
     secure: M5QsspiAtEP8jLdfNQ5e+e0v9dp8vVkDJfX4NEdsOrd2DMsr+WhPZEFTbqtnWk10
   artifact: ducible
   draft: false
   prerelease: false
   on:
     branch: master
     appveyor_repo_tag: true
